### ISSUE TITLE
Improving error messages

### ISSUE THREAD

**Issue by leos313** [des-cei/artico3#1]
When no more artico3 slots are loaded in the FPGA, and/or no more artico3 structures in the sw memory (for example after a `artico3_exit()` or `artico3_release()` or before `artico3_init()`) are allocated, if we try to access an artico3 hardware structure (that clearly does not exit), a Segmentation Fault is generated. 
Instead, a message like *no artico3 structure available* can make the sw debug easier. 

That is not a bug but a future error message improvement (I cannot assign the label **improvement** because I do not have the right).

**Comment by alfonrod** [comment]
The scenarios you describe are exactly the same as trying to access a pointer before ```malloc``` or after ```free``` (not a good idea, right?).  Hence, it does not really make sense to implement fancy error messages.

It is the **programmer's responsibility** to make sure they do not:
- use ARTICo³ before ```artico3_init``` (system will crash, since no full bitstream is present in the FPGA) or after ```artico3_exit```
- use a kernel before ```artico3_kernel_create``` or after ```artico3_kernel_release```
- use a kernel port / shared memory buffer before ```artico3_alloc``` or after ```artico3_free```

In addition, you can always **use the return value of all the functions available in the runtime library API to implement proper error handling** in your application (again, this is up to the programmer).
